### ISSUE TITLE
Loosening pinning to 'x' instead of 'x.x'?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/libxcb-feedstock#20]
### Comment:

I noticed that this package isn't in the global pinnings which caused some issues in https://github.com/conda-forge/libva-feedstock/pull/37 when libxcb version "1.16" was pulled in and other packages are built with `1.15`.

Does it make sense to loosen the pinning?

Otherwise, I can start a migration with the 1.16 as the version number.

Let me know.

**Comment by ehfd** [comment]
So far: https://abi-laboratory.pro/index.php?view=timeline&l=libxcb

**Comment by isuruf** [comment]
@pkgw, what do you think?

**Comment by isuruf** [comment]
I can send a PR if @conda-forge/libxcb thinks pinning to major is okay

**Comment by pkgw** [comment]
Sorry for being slow — yeah, I think it should be OK to loosen the pinning. It's a stable library and I suspect that upstream is going to be quite sensitive to ABI compatibility these days.

**Comment by isuruf** [comment]
PR for loosening on built packages https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/863

**Comment by pkgw** [comment]
And https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6468
